// Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

// Remove proxy settings if they exist
// systemProp.http.proxyHost=
// systemProp.http.proxyPort=
// systemProp.https.proxyHost=
// systemProp.https.proxyPort=

android.useAndroidX=true
android.enableJetifier=true

org.gradle.parallel=true
org.gradle.caching=true
